version: 2
updates:
  # Maintain dependencies for pip packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for workflow files in the default location
    directory: "/"
    # Check for updates daily (options: daily, weekly, monthly)
    schedule:
      interval: "weekly"
      day: "saturday"
