version: '2.2'
services:
  hpotter:
    build: .
    init: true
    ports:
      - "22:22"
      - "23:23"
      - "80:8080"
    depends_on: 
      - postgres
    networks:
      - backend
    environment:
      HPOTTER_DB: postgresql
      HPOTTER_DB_USER: ${HPOTTER_DB_USER}
      HPOTTER_DB_PASSWORD: ${HPOTTER_DB_PASSWORD}
      HPOTTER_DB_HOST: postgres
      HPOTTER_DB_PORT: 5432
      HPOTTER_DB_DB: ${HPOTTER_DB_DB}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  jsonserver:
    build: .
    ports:
      - "8000:8000"
    depends_on: 
      - postgres
    networks:
      - backend
    environment:
      HPOTTER_DB: postgresql
      HPOTTER_DB_USER: ${HPOTTER_DB_USER}
      HPOTTER_DB_PASSWORD: ${HPOTTER_DB_PASSWORD}
      HPOTTER_DB_HOST: postgres
      HPOTTER_DB_PORT: 5432
      HPOTTER_DB_DB: ${HPOTTER_DB_DB}
    restart: always
    command: 'hpotter.jsonserver'
    
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: ${HPOTTER_DB_DB}
      POSTGRES_USER: ${HPOTTER_DB_USER}
      POSTGRES_PASSWORD: ${HPOTTER_DB_PASSWORD}
    networks:
      - backend
    restart: always
    volumes:
     - db_data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  db_data: {}
